services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: GeeXPert
      MYSQL_USERNAME: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://ollama:11434/api/tags" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  backend:
    build: .
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - 'DATABASE_URL:${DATABASE_URL}'
      - 'DATABASE_USERNAME:${DATABASE_USERNAME}'
      - 'DATABASE_PASSWORD:${DATABASE_PASSWORD}'
      - 'IGBD_ID:${IGBD_ID}'
      - 'IGBD_KEY:${IGBD_KEY}'
      - 'JWT_KEY:${JWT_KEY}'

volumes:
  db_data:
  ollama_data:
